version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: username  # Set your username
      POSTGRES_PASSWORD: password  # Set your password
      POSTGRES_DB: ms-card  # Set your database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persist data for Redis

volumes:
  postgres_data:  # Named volume for Postgres data persistence
  redis_data:     # Named volume for Redis data persistence
